Repository next-step/js-todo-list-step1, pull requests merged in 2020-10, with the labels that each got.

#29 [3기 황준일] ToDoList CRUD
  .gitignore
  README.md
  index.html
  src/App.js
  src/components/ToDoCount.js
  src/components/ToDoFilter.js
  src/components/ToDoInput.js
  src/components/ToDoList.js
  src/components/index.js
  src/constants/FilterTypes.js
  src/core/Component.js
  src/core/Store.js
  src/storage/index.js
  src/store/toDoStore.js
  src/utils/index.js
Labels: TeamA, 🏆 미션완료, 🚀 필수미션, 🚀🚀 심화미션

#30 [3기 전환오] TodoList with CRUD
  .gitignore
  .prettierrc
  components/App.js
  components/TodoCount.js
  components/TodoFilter.js
  components/TodoInput.js
  components/TodoItem.js
  components/TodoList.js
  constants/index.js
  css/style.css
  index.html
  index.js
  package-lock.json
  package.json
  templates/index.js
Labels: TeamA, 🚀 필수미션, 🚀🚀 심화미션

#31 [3기 catsbi] TodoList with CRUD
  index.html
  js/LocalStorageHelper.js
  js/index.js
Labels: TeamA, 🚀 필수미션, 🚀🚀 심화미션

#33 [3기 권준혁] TodoList with CRUD
  src/index.js
Labels: TeamB, 🚀 필수미션, 🚀🚀 심화미션

#34 [3기 김동하] TodoList with CRUD
  .prettierrc
  css/todo.md
  js/app.js
  js/components/TodoFooter.js
  js/components/TodoItem.js
  js/components/TodoList.js
  js/reducer.js
  js/redux.js
  js/utils.js
Labels: TeamB, 🚀 필수미션, 🚀🚀 심화미션

#35 [3기 박은영] TodoList with CRUD
  .gitignore
  index.html
  src/app.js
  src/components/TodoEditItem.js
  src/components/TodoFilters.js
  src/components/TodoItem.js
  src/components/TodoList.js
  src/components/TodoViewItem.js
  src/constant.js
  src/css/style.css
  src/dom.js
  src/registEvent.js
  src/render.js
  src/store.js
Labels: TeamB, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#36 [3기 나무] TodoList with CRUD
  .eslintignore
  .eslintrc.js
  .gitignore
  .prettierrc
  1주차.md
  README.md
  index.html
  js/TodoCount.js
  js/TodoInput.js
  js/TodoList.js
  js/app.js
  js/constants.js
  src/TodoCount.js
  src/TodoFilter.js
  src/TodoInput.js
  src/TodoList.js
  src/app.js
  src/constants.js
Labels: TeamC, 🐞 버그, 🚀 필수미션

#37 [3기 dotol] TodoList with CRUD
  index.html
  js/ItemController.js
  js/TodoCount.js
  js/TodoInput.js
  js/TodoItem.js
  js/TodoList.js
  js/TodoState.js
  js/main.js
  js/render.js
  js/utils.js
Labels: TeamC, 🚀 필수미션

#38 [3기 안동민] TodoList with CRUD
  .vscode/settings.json
  index.html
  js/app.js
  js/components/ToDoCount.js
  js/components/ToDoFilter.js
  js/components/ToDoInput.js
  js/components/ToDoList.js
  js/store/store.js
  js/store/storeConfig.js
Labels: TeamC, 🚀 필수미션, 🚀🚀 심화미션

#40 [3기 journey] TodoList with CRUD
  .gitignore
  index.html
  js/class/ToDo.js
  js/class/ToDoApplication.js
  js/class/ToDoItem.js
  js/class/ToDoRepository.js
Labels: TeamD, 🚀 필수미션, 🚀🚀 심화미션

#41 [3기 김휘겸] TodoList with CRUD
  README.md
  css/todo.md
  index.html
  js/app.js
  js/filterItem.js
  js/todoItem.js
Labels: TeamD, 🚀 필수미션

#42 [3기 kingso] TodoList with CRUD
  .vscode/settings.json
  README.md
  index.html
  src/TodoApp.js
Labels: TeamD, 🚀 필수미션

#44 [3기 Austin] TodoList with CRUD
  README.md
  index.html
  index.js
  package.json
Labels: TeamE, 🚀 필수미션

#45 [3기 김종완] TodoList with CRUD
  .gitignore
  index.html
  js/App.js
Labels: TeamE, 🚀 필수미션, 🚀🚀 심화미션

#46 [3기 Rachel] TodoList with CRUD
  .idea/.gitignore
  .idea/js-todo-list-step1.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  app.js
  index.html
  src/components/TodoApp.js
  src/components/TodoCount.js
  src/components/TodoFilter.js
  src/components/TodoInput.js
  src/components/TodoItem.js
  src/components/TodoList.js
  src/utils/constants.js
Labels: TeamE, 🚀 필수미션

#47 [3기 seung15] TodoList with CRUD
  .gitignore
  .idea/codeStyles/codeStyleConfig.xml
  .idea/js-todo-list-step1.iml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  index.html
  js/Storage.js
  js/TodoApp.js
  js/TodoCount.js
  js/TodoInput.js
  js/TodoItem.js
  js/TodoList.js
Labels: TeamF, 🚀 필수미션, 🚀🚀 심화미션
