Repository next-step/js-todo-list-step1, pull requests merged in 2020-11, with the labels that each got.

#48 [4기 knae11] TodoList with CRUD
  App.js
  README.md
  components/todoCount.js
  components/todoInput.js
  components/todoList.js
  css/style.css
  index.html
  index.js
Labels: TeamA, 🚨 리뷰 요청

#49 [4기 wonsunil] TodoList
  index.html
  src/TodoApp.js
  src/components/TodoCounter.js
  src/components/TodoFilters.js
  src/components/TodoInput.js
  src/components/TodoList.js
  src/core/Component.js
  src/index.js
Labels: TeamA, 🏆 미션완료, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#50 [4기 이재준] TodoList with CRUD
  .gitignore
  README.md
  index.html
  src/Components/App.js
  src/Components/TodoInput.js
  src/Components/TodoList.js
  src/index.js
  src/reducer/todo.js
  src/utils/createRandomId.js
  src/utils/element-utils.js
  src/utils/my-redux.js
Labels: TeamA, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#51 [4기 minsung03] TodoList with CRUD
  .gitignore
  index.html
  js/app.origin.js
  js/app.solution.js
Labels: TeamB, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#52 [4기 노승재] TodoList
  index.html
  js/script.js
Labels: TeamB, 🚀 필수미션, 🚨 리뷰 요청

#53 [4기 one] TodoList CRUD
  .eslintrc
  .gitignore
  .huskyrc
  .lintstagedrc
  .prettierrc
  css/style.css
  index.html
  package.json
  src/css/style.css
  src/index.js
  src/js/TodoController.js
  src/js/TodoModel.js
  src/js/TodoView.js
  yarn.lock
Labels: TeamB, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#54 [4기 홍석훈] TodoList CRUD
  index.html
  src/db.js
  src/filter.js
  src/index.js
  src/newInput.js
  src/store.js
  src/todo.js
  src/todos.js
  src/utils.js
Labels: TeamC, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#55 [4기 Vicky] TodoList CRUD
  App.js
  components/TodoCount.js
  components/TodoInput.js
  components/TodoList.js
  components/TodoStatus.js
  index.html
  utils/constantsKey.js
  utils/handleData.js
  utils/handleStorage.js
Labels: TeamC, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#56 [4기 김휘겸] TodoList CRUD
  js/TodoList/KeyVariable.js
  js/TodoList/README.md
  js/TodoList/Templates.js
  js/TodoList/TodoFilter.js
  js/TodoList/TodoInput.js
  js/TodoList/TodoList.js
  js/app.js
Labels: TeamC, 🚨 리뷰 요청

#57 [4기 성현준] TodoList CRUD
  README.md
  index.html
  js/createElement.js
  js/filter.js
  js/handleState.js
  js/handleTodoItem.js
  js/selectElement.js
Labels: TeamD, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#58 [4기 younho9] TodoList with CRUD
  README.md
  index.html
  src/components/App.js
  src/components/Filter.js
  src/components/TodoItem.js
  src/components/TodoList.js
  src/index.js
  src/store/todoStore.js
  src/utils/action.js
  src/utils/createElement.js
  src/utils/utils.js
Labels: TeamD, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#59 [4기 박병길] TodoList CRUD
  .vscode/settings.json
  README.md
  index.html
  js/components/App.js
  js/components/TodoCount.js
  js/components/TodoInput.js
  js/components/TodoList.js
  js/components/TodoTab.js
  js/domain/todo.js
  js/domain/todoRepository.js
  js/domain/todos.js
  js/index.js
  js/utils/constants.js
  js/utils/templates.js
  js/utils/validators.js
Labels: TeamD, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#60 [4기 Sarah1446] TodoList with CRUD
  App.js
  components/TodoCount.js
  components/TodoFilter.js
  components/TodoInput.js
  components/TodoList.js
  components/utils/newId.js
  index.html
  index.js
  package-lock.json
Labels: TeamE, ❓질문, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#61 [4기 my-u] TodoList with CRUD
  index.html
  todoList.js
Labels: TeamE, 🚨 리뷰 요청

#62 [4기 devhyun637] TodoList with CRUD
  index.html
  index.js
  js/App.js
  js/components/InputTodo.js
  js/components/TodoCount.js
  js/components/TodoList.js
  js/components/TodoStorage.js
  js/utils/createId.js
Labels: TeamE, ❓질문, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청
