Repository next-step/js-todo-list-step1, pull requests merged in 2021-03, with the labels that each got.

#130 [7기 younoah] TodoList CRUD
  .history/js/todo_20210202224825.js
  .history/js/todo_20210211234316.js
  index.html
  js/todo.js
  src/TodoApp.js
  src/TodoFilter.js
  src/TodoInput.js
  src/TodoList.js
  src/index.js
  src/utils.js
Labels: TeamA, 🏆 미션완료, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#131 [7기 YunNote] TodoList CRUD
  .gitignore
  css/style.css
  index.html
  javascripts/components/TodoApp.js
  javascripts/components/TodoCount.js
  javascripts/components/TodoFilter.js
  javascripts/components/TodoInput.js
  javascripts/components/TodoList.js
  javascripts/components/TodoListItem.js
  javascripts/components/todo-item/TodoItemCheckBox.js
  javascripts/components/todo-item/TodoItemDestroy.js
  javascripts/components/todo-item/TodoItemTitle.js
  javascripts/components/todo-item/TodoItemUpdateTitle.js
  javascripts/components/todo-item/TodoItemWrapper.js
  javascripts/index.js
  javascripts/utils/ItemFilter.js
  javascripts/utils/KeyUtils.js
  javascripts/utils/Storage.js
Labels: TeamA, 🏆 미션완료, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#132 [7기 윤성학] TodoList with CRUD
  .gitignore
  index.html
  js/Store/CustomLocalStorage.js
  js/Store/TodoStore.js
  js/TodoApp.js
  js/controller/TodoFilterController.js
  js/controller/TodoItemController.js
  js/controller/TodoWriterController.js
  js/service/TodoFilterService.js
  js/service/TodoItemService.js
  js/service/TodoWriterService.js
  js/utils/constants.js
  js/utils/templates.js
  js/view/TodoView.js
Labels: TeamA

#133 [7기 TaeBeomShin] TodoList CRUD
  index.html
  todo.js
  todofilter.js
Labels: TeamB

#134 [7기 inhyuck] TodoList with CRUD
  .gitignore
  consts/todoFilterType.js
  index.html
  index.js
  js/components/TodoApp.js
  js/components/TodoInput.js
  js/components/TodoList.js
  js/utils/generateId.js
  store/todoStore.js
Labels: TeamB, 🏆 미션완료, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#135 [7기 Jay] TodoList CRUD
  index.html
  js/main.js
Labels: TeamB

#136 [7기 6mn12j] TodoList CRUD
  component/toDoFilter.js
  component/toDoInput.js
  component/toDoList.js
  src/app.js
  src/index.html
  src/init.js
  src/toDoLocalStorage.js
Labels: TeamC, 🏆 미션완료, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#137 [7기 이하늘] TodoList with CRUD
  index.html
  index.js
Labels: TeamC, 🚀 필수미션, 🚨 리뷰 요청

#138 Romanticcoder
  css/style.css
  index.html
  todo.js
Labels: TeamC

#139 [7기 차정수] TodoList with CRUD
  components/CounterContainer.js
  components/TodoApp.js
  components/TodoFilters.js
  components/TodoInput.js
  components/TodoItem.js
  components/TodoList.js
  index.html
  index.js
  models/Item.js
  utils/constants.js
Labels: TeamD, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#140 [7기 pul8219] TodoList with CRUD
  index.html
  js/addTodo.js
  js/app.js
  js/checkTodo.js
  js/deleteTodo.js
  js/editTodo.js
  js/todoRender.js
  js/todoTrigger.js
Labels: TeamD, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#141 [7기 임수지] TodoList CRUD
  index.html
  src/index.js
  src/todoApp.js
  src/todoInput.js
  src/todoList.js
  src/todoStatus.js
  src/util.js
Labels: TeamD, 🏆 미션완료, 🚀 필수미션, 🚨 리뷰 요청
