Repository next-step/js-todo-list-step1, pull requests merged in 2021-01, with the labels that each got.

#71 [5기 나무] TodoList with CRUD
  README.md
  src/TodoList.js
  src/app.js
Labels: TeamA, 🚀 필수미션, 🚀🚀 심화미션

#74 [5기 Junho U] TodoList with CRUD
  index.html
  js/components/app.js
  js/components/list.js
  js/components/task.js
  js/main.js
  js/render.js
  js/test/Todo.test.js
Labels: TeamA, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#75 [5기 김영재] TodoList with CRUD
  .gitignore
  TodoApp.js
  TodoCount.js
  TodoFilter.js
  TodoInput.js
  TodoList.js
  constants.js
  index.html
  index.js
  package.json
  utils.js
  yarn.lock
Labels: TeamA, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#76 [5기 Minsiki] TodoList with CRUD
  debug.log
  index.html
  js/component/TodoApp.js
  js/component/TodoInput.js
  js/component/TodoList.js
  js/index.js
Labels: TeamB

#77 [5기 WOO] TodoList with CRUD
  .DS_Store
  .gitignore
  README.md
  index.html
  js/App.js
  js/component/TodoCount.js
  js/component/TodoFilter.js
  js/component/TodoInput.js
  js/component/TodoList.js
  js/store/index.js
  js/store/module/filter.js
  js/store/module/todo.js
  js/store/storage.js
  js/utils/constants.js
  js/utils/templates.js
Labels: TeamB, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#78 [5기 hhwaaaaa1] TodoList with CRUD
  README.md
  index.html
  js/TodoFilter.js
  js/TodoItem.js
  js/TodoList.js
  js/TodoRegister.js
  js/main.js
  js/useStorage.js
Labels: TeamB, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#79 [5기 조성재] TodoList with CRUD
  .gitignore
  README.md
  component/TodoApp.js
  component/TodoCount.js
  component/TodoFilter.js
  component/TodoInput.js
  component/TodoItem.js
  component/TodoList.js
  index.html
  index.js
  js/LocalStorageUtil.js
  package.json
Labels: TeamC, 🚀🚀 심화미션, 🚨 리뷰 요청

#80 [5기 HeeSang] TodoList
  .gitignore
  index.html
  index.js
  js/TodoApp.js
  js/TodoCount.js
  js/TodoFilters.js
  js/TodoInput.js
  js/TodoItem.js
  js/TodoList.js
Labels: TeamC

#82 [5기 김휘겸] TodoList with CRUD
  js/TodoList/KeyVariable.js
  js/TodoList/README.md
  js/TodoList/Templates.js
  js/TodoList/TodoFilter.js
  js/TodoList/TodoInput.js
  js/TodoList/TodoList.js
  js/TodoListApp/components/TodoFilter.js
  js/TodoListApp/components/TodoInput.js
  js/TodoListApp/components/TodoList.js
  js/TodoListApp/index.js
  js/TodoListApp/lib/component.js
  js/TodoListApp/lib/pubsub.js
  js/TodoListApp/store/actions.js
  js/TodoListApp/store/index.js
  js/TodoListApp/store/mutations.js
  js/TodoListApp/store/state.js
  js/TodoListApp/store/store.js
  js/TodoListApp/util/keyCode.js
  js/app.js
  js/filterItem.js
  js/todoItem.js
Labels: TeamD, 🚨 리뷰 요청

#85 [5기 realhee] TodoList with CRUD
  README.md
  index.html
  js/TodoApp.js
  js/TodoInput.js
  js/TodoList.js
Labels: TeamD

#86 [5기 Jamieshin0201] TodoList with CRUD
  index.html
  js/main.js
Labels: TeamE, 🚨 리뷰 요청

#87 [5기 이은결] TodoList with CRUD
  index.html
  js/toDo.js
Labels: TeamE, 🚀 필수미션, 🚨 리뷰 요청

#88 [5기 한정원] TodoList with CRUD
  index.html
  src/App.js
  src/components/count.js
  src/components/filter.js
  src/components/input.js
  src/components/list.js
  src/lib/component.js
  src/lib/pubsub.js
  src/store/actions.js
  src/store/index.js
  src/store/localStorage.js
  src/store/mutations.js
  src/store/state.js
  src/store/store.js
Labels: TeamE, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#89 [5기 김우정] TodoList with CRUD
  .gitignore
  index.html
  js/todo.js
Labels: TeamC

#90 [5기 이정섭] TodoList with CRUD
  index.html
  index.js
Labels: TeamF, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#91 [5기 서지환] TodoList with CRUD
  README.md
  TodoApp.js
  components/TodoCount.js
  components/TodoFilters.js
  components/TodoList.js
  components/index.js
  index.html
  index.js
Labels: TeamF, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#92 [5기 김수정] TodoList with CRUD
  README.md
  css/style.css
  index.html
  src/App.js
  src/components/TodoCount.js
  src/components/TodoFilters.js
  src/components/TodoInput.js
  src/components/TodoItem.js
  src/components/TodoList.js
  src/components/index.js
  src/core/Component/index.js
  src/enums/Filter.js
  src/index.js
  src/modules/index.js
  src/modules/todo/index.js
  src/modules/todo/reducer.js
  src/redux/index.js
  src/redux/redux.js
  src/utils/Storage.js
Labels: TeamF, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#93 [5기 조윤호] TodoList with CRUD
  .eslintrc.json
  .gitignore
  .prettierrc
  README.md
  class/app.js
  index.html
  package-lock.json
  package.json
  src/event/triggerClickEvent.js
  src/event/triggerDoubleClickEvent.js
  src/event/triggerKeyupEvent.js
  src/index.js
  src/render/render.js
  src/todoList/addTodoItem.js
  src/todoList/countTodoItem.js
  src/todoList/editTodoItem.js
  src/todoList/removeTodoItem.js
  src/todoList/toggleTodoItem.js
Labels: TeamG, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#95 [5기 조은현] TodoList with CRUD
  .eslintrc.json
  .gitignore
  .prettierrc
  README.md
  index.html
  src/controllers/TodoApp.js
  src/index.js
  src/models/Todo.js
  src/todoStorage.js
  src/utils/constants.js
  src/views/TodoCountView.js
  src/views/TodoFilterView.js
  src/views/TodoInputView.js
  src/views/TodoListResultView.js
  src/views/Views.js
Labels: TeamG, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#84 [5기 정혜지] TodoList with CRUD
  .idea/workspace.xml
  index.html
Labels: TeamD
