Repository next-step/js-todo-list-step1, pull requests merged in 2021-02, with the labels that each got.

#101 [6기 kwonkyu] TodoList with CRUD
  application.js
  common.js
  filterview.js
  index.html
  todoelement.js
Labels: TeamA, 🏆 미션완료, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#102 [6기 suppplier] TodoList with CRUD
  index.html
  js/AddNewItem.js
  js/ControlTodoButton.js
  js/ControlTodoItems.js
  js/TodoLocalStorage.js
  js/index.js
  package.json
Labels: TeamA, 🏆 미션완료, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#103 [6기 khw970421] TodoList with CRUD
  index.html
  src/index.js
Labels: TeamA, 🏆 미션완료, 🚀 필수미션, 🚨 리뷰 요청

#105 [6기 hongjehong] TodoList with CRUD
  .gitignore
  README.md
  index.html
  main.js
  src/App.js
Labels: TeamB, 🏆 미션완료, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#106 [6기 조윤호]TodoList with CRUD
  .eslintrc.json
  class/app.js
  index.html
  package-lock.json
  package.json
  src/App.js
  src/components/AddTodo.js
  src/components/ChangeTodo.js
  src/components/EditTodo.js
  src/components/FilterTodo.js
  src/constant/state.js
  src/event/triggerClickEvent.js
  src/event/triggerDoubleClickEvent.js
  src/event/triggerKeyupEvent.js
  src/index.js
  src/render/render.js
  src/todoList/addTodoItem.js
  src/todoList/countTodoItem.js
  src/todoList/editTodoItem.js
  src/todoList/removeTodoItem.js
  src/todoList/toggleTodoItem.js
Labels: TeamB, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#107 [6기 DD] TodoList with CRUD
  .vscode/settings.json
  css/style.css
  index.html
  src/TodoApp.js
  src/components/TodoList.js
  src/components/todoAppender.js
  src/components/todoFilter.js
  src/core/Component.js
  src/main.js
  temp.html
Labels: TeamB, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#108 [6기 6mn12j] TodoList with CRUD
  README.md
  component/constant.js
  component/todoCount.js
  component/todoEdit.js
  component/todoFilter.js
  component/todoList.js
  component/todoLocalStorage.js
  css/style.css
  index.html
  init.js
  todoApp.js
  페어_프로그래밍_회고.md
Labels: TeamC, 🏆 미션완료, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#111 [6기 Jiseon Kim] TodoList with CRUD
  index.html
  package.json
  src/app.js
  src/components/todoCheckbox.js
  src/components/todoCount.js
  src/components/todoEdit.js
  src/components/todoFilter.js
  src/components/todoInput.js
  src/localStorage/loadTodo.js
  src/localStorage/localStorage.js
  src/main.js
  src/todoDOM.js
Labels: TeamC, 🏆 미션완료, 🚀 필수미션, 🚨 리뷰 요청

#114 [6기 시경덕] TodoList with CRUD
  .gitignore
  index.html
  js/TodoApp.js
  js/TodoCount.js
  js/TodoInput.js
  js/TodoList.js
  js/index.js
  js/utils.js
Labels: TeamD, 🏆 미션완료, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#115 [6기 박소현] TodoList with CRUD
  .eslintrc.json
  .gitignore
  .prettierrc
  index.html
  package-lock.json
  package.json
  src/components/Filters.js
  src/components/NewTodoInput.js
  src/components/TodoCount.js
  src/components/TodoItem.js
  src/components/TodoList.js
  src/css/style.css
  src/model/TodosModel.js
  src/scripts/index.js
  src/subjects/Observer.js
  src/subjects/Subject.js
  src/subjects/TodosSubject.js
Labels: TeamD, 🏆 미션완료, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#116 [6기 김동환] TodoList with CRUD
  LocalStorageSupporter.js
  app.js
  component/TodoApp.js
  component/TodoInput.js
  component/TodoList.js
  component/TodoTotalCount.js
  index.html
Labels: TeamE, 🏆 미션완료, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청, 🛠️ 리팩토링

#117 [6기 my_U] TodoList with CRUD
  todoList.js
Labels: TeamE, 🚀 필수미션, 🚨 리뷰 요청

#118 [6기 pul8219] TodoList With CRUD
  app.js
  index.html
  utils.js
Labels: TeamE, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#119 [6기 WOO] TodoList with CRUD
  .eslintrc.js
  .gitignore
  README.md
  index.html
  js/App.js
  js/component/TodoCount.js
  js/component/TodoFilter.js
  js/component/TodoInput.js
  js/component/TodoList.js
  js/store/module/filter.js
  js/store/module/todo.js
  js/utils/constants.js
  js/utils/templates.js
  package-lock.json
  package.json
  src/App.js
  src/component/TodoCount.js
  src/component/TodoFilter.js
  src/component/TodoInput.js
  src/component/TodoList.js
  src/component/TodoListItem.js
  src/domain/Todo.js
  src/index.js
  src/store/index.js
  src/store/module/todo.js
  src/store/storage.js
  src/utils/FILTER.js
  src/utils/createElement.js
Labels: TeamF, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#122 [6기 yeewon] TodoList with CRUD
  .vscode/settings.json
  index.html
  js/AddNewTodoItem.js
  js/ControlFilterButton.js
  js/ControlLocalStorage.js
  js/ControlTodoItem.js
  js/EditTodoItem.js
  js/index.js
Labels: TeamF, 🏆 미션완료, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청

#123 [6기 younoah] TodoList with CRUD
  .gitignore
  .history/js/todo_20210202224825.js
  .history/js/todo_20210211234316.js
  index.html
  js/todo.js
Labels: TeamF, 🚀 필수미션, 🚀🚀 심화미션, 🚨 리뷰 요청
